name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: shashikalyankalepu/valcraa@master
        env:
          ado_token: "7w4jrrujuhw3fcvdm2jxyknmravljvrajp7biuq6w7agmligmdda"
          github_token: "2d7d5bfcc14e3b0a47a6d2fa1ee2a4cb1c56bcca"
          ado_organization: "ado_organization_name"
          ado_project: "valcraa"
          ado_area_path: "optional_area_path\\optional_area_path"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
